version: 2

references:
  install-dependencies: &install-dependencies
    run:
      name: Install dependencies
      command: |
        sudo dpkg --add-architecture i386;
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
        sudo apt-get -y -qq update;
        sudo apt-get -y install gcc-powerpc-linux-gnu gcc-arm-linux-gnueabi \
                                libc6-dev-armel-cross gcc-aarch64-linux-gnu \
                                libc6-dev-arm64-cross;

jobs:
  test0:
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    steps:
      - checkout
      - *install-dependencies
      - run:
          name: Test
          command: |
            cc -v; CFLAGS="-O0 -Werror" make all && make clean;
            make c99build     && make clean;
            make c11build     && make clean;
            make aarch64build && make clean;
            make -j regressiontest && make clean;
            make shortest     && make clean;
            make cxxtest      && make clean;
  test1:
    docker:
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    steps:
      - checkout
      - *install-dependencies
      - run:
          name: Test
          command: |
            make gnu90build   && make clean;
            make gnu99build   && make clean;
            make ppc64build   && make clean;
            make ppcbuild     && make clean;
            make armbuild     && make clean;
            make -C tests test-legacy test-longmatch test-symbols && make clean;
            make -C lib libzstd-nomt && make clean;
  publish-github-release:
    docker:
      - image: cibuilds/github:0.12.0
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add -q make gzip
      - run:
          name: Publish
          command: |
            export VERSON=zstd-$CIRCLE_TAG;
            git archive $CIRCLE_TAG --prefix "$VERSION/" --format tar \
                        -o zstd-source.tar;
            gzip -9 zstd-source.tar;
            sha256sum zstd-source.tar.gz > zstd-source.tar.gz.sha256sum;
            mkdir -p "$CIRCLE_ARTIFACTS";
            cp zstd-source.tar.gz{,.sha256sum} "$CIRCLE_ARTIFACTS";
            if [ ! -z $GITHUB_TOKEN ]; then;
              ghr --token "$GITHUB_TOKEN" \
                  --repository "$CIRCLE_PROJECT_REPONAME" \
                  --username "$CIRCLE_PROJECT_USERNAME"
                  "$VERSION" "$CIRCLE_ARTIFACTS";
            fi;
      - store_artifacts:
          path: /tmp/circleci-artifacts

workflows:
  version: 2
  commit:
    jobs:
      # - test0:
      #     filters:
      #       tags:
      #         only: /.*/
      # - test1:
      #     filters:
      #       tags:
      #         only: /.*/
      - publish-github-release:
          # requires:
          #   - test0
          #   - test1
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

  # Longer tests
    #- make -C tests test-zstd-nolegacy && make clean
    #- pyenv global 3.4.4; make -C tests versionsTest && make clean
    #- make zlibwrapper         && make clean
    #- gcc -v; make -C tests test32 MOREFLAGS="-I/usr/include/x86_64-linux-gnu" && make clean
    #- make uasan               && make clean
    #- make asan32              && make clean
    #- make -C tests test32 CC=clang MOREFLAGS="-g -fsanitize=address -I/usr/include/x86_64-linux-gnu"
  # Valgrind tests
    #- CFLAGS="-O1 -g" make -C zlibWrapper valgrindTest && make clean
    #- make -C tests valgrindTest && make clean
  # ARM, AArch64, PowerPC, PowerPC64 tests
    #- make ppctest             && make clean
    #- make ppc64test           && make clean
    #- make armtest             && make clean
    #- make aarch64test         && make clean
